apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node02
      containers:
        - name: productpage
          image: istio/examples-bookinfo-productpage-v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 9080
          env:
            - name: REVIEWS_HOSTNAME
              value: reviews
            - name: RATINGS_HOSTNAME
              value: ratings
            - name: DETAILS_HOSTNAME
              value: details
