apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: productpage
  name: productpage
  namespace: frontend
spec:
  ports:
  - name: 9080-9080
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: productpage
  type: ClusterIP
status:
  loadBalancer: {}
