apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: docker.io/istio/examples-bookinfo-ratings-v2:1.20.2
          imagePullPolicy: IfNotPresent
          env:
            # ratings-v2 will use mongodb as the default db backend.
            # if you would like to use mysqldb then you can use this file
            # which sets DB_TYPE = 'mysql' and the rest of the parameters shown
            # here and also create the # mysqldb service using bookinfo-mysql.yaml
            # NOTE: This file is mutually exclusive to bookinfo-ratings-v2.yaml
            - name: DB_TYPE
              value: "mysql"
            - name: MYSQL_DB_HOST
              value: mysqldb
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USER
              value: root
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: rootpasswd
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9080
