apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: details
  name: details
  namespace: backend
spec:
  ports:
  - name: 9080-9080
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: details
  type: ClusterIP
status:
  loadBalancer: {}
